# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Setups up Starter for new project and sets values as described"
  lane :setup_project do
  	project_name = prompt(text: "What's the project name?")
  	app_name = prompt(text: "What's the app name?")
  	git_origin_url = prompt(text: "What's the new git repo url?")
  	main_repo_branch = prompt(text: "What's the main repo branch? (main or master)")

	sh("cp -r ../../Starter ../../" + project_name)
	sh("cd ../../" + project_name) 
	sh("cd ../../" + project_name + " && git remote set-url origin " + git_origin_url)
	sh("cd ../../" + project_name + " && git fetch")
	sh("cd ../../" + project_name + " && git checkout " + main_repo_branch)
	sh("cd ../../" + project_name + " && mv Starter " + project_name)
	sh("cd ../../" + project_name + " && mv StarterUITests " + project_name + "UITests")
	sh("cd ../../" + project_name + " && mv StarterTests " + project_name + "Tests")
	sh("cd ../../" + project_name + " && mv Starter.xcodeproj " + project_name + ".xcodeproj")

	sh("cd ../../" + project_name + " && rm -rf Starter.xcworkspace")
	sh("cd ../../" + project_name + " && pod deintegrate")
	sh("cd ../../" + project_name + " && rm -rf Pods/")

	sh("cd ../../" + project_name + " && /usr/libexec/PlistBuddy -c 'Set :CFBundleName " + app_name + "' " + project_name + "/Info.plist")

	sh("cd ../../" + project_name + " && sed -i '' 's/Starter/" + project_name + "/g' " + project_name + ".xcodeproj/project.pbxproj")
	sh("cd ../../" + project_name + " && sed -i '' 's/Starter/" + project_name + "/g' Podfile")
	sh("cd ../../" + project_name + " && pod install")

	sh("cd ../../" + project_name + " && git commit --all -m 'Setup new project'")
	sh("cd ../../" + project_name + " && git push")
  end

end
